- name: Ensure repository key for z-push is in place
  apt_key: url=http://repo.z-hub.io/z-push:/final/Debian_9.0/Release.key state=present
  tags:
    - dependencies

- name: Add z-push repository
  apt_repository: repo='deb http://repo.z-hub.io/z-push:/final/Debian_9.0/ /'
  tags:
    - dependencies

- name: Install required packages for z-push
  apt: pkg={{ item }} state=installed
  with_items:
    - z-push-config-apache
    - z-push-backend-imap
  tags:
    - dependencies

- name: Ensure z-push state and log directories are in place
  file: state=directory path={{ item }} owner=www-data group=www-data mode=0755
  with_items:
    - /decrypted/zpush-state
    - /var/log/z-push
  notify: restart apache

- name: Update z-push config.php
  template: src=usr_share_z-push_config.php.j2 dest=/usr/share/z-push/config.php

- name: Update z-push imap backend config.php
  copy: src=usr_share_z-push_backend_imap_config.php dest=/usr/share/z-push/backend/imap/config.php

- name: Configure z-push logrotate
  copy: src=etc_logrotate_z-push dest=/etc/logrotate.d/z-push owner=root group=root mode=0644
