- name: Determine whether roundcube is configured
  stat: path=/var/www/roundcube/config.inc.php
  register: roundcube_config

- name: Install roundcube dependencies
  apt: pkg={{ item }} state=present
  with_items:
    - php7.0
    - php7.0-sqlite3
    - php7.0-mcrypt
    - php7.0-gd
    - php7.0-pspell
    - php7.0-intl
    - php7.0-curl
    - php7.0-mbstring
    - aspell
    - aspell-en
    - composer
  tags:
    - dependencies

- name: Clone roundcube
  become_user: www-data
  git: repo=https://github.com/roundcube/roundcubemail.git
       dest=/var/www/roundcube
       version={{ webmail_version }}
       update=no
       accept_hostkey=yes

- name: Initialize composer
  become_user: www-data
  command: composer install --no-dev
           chdir=/var/www/roundcube
           creates=/var/www/roundcube/vendor/autoload.php

- name: Remove installer directory
  file: path=/var/www/roundcube/installer state=absent

- name: Install Roundcube configuration
  template: src=var_www_roundcube_config_config.inc.j2 dest=/var/www/roundcube/config/config.inc.php

- name: Install javascript dependencies
  command: ./install-jsdeps.sh
           chdir=/var/www/roundcube/bin
           creates=/var/www/roundcube/program/js/jquery.min.js

- name: Create db directory
  file: path=/decrypted/roundcube group=www-data mode=0775 state=directory

- name: Make logs and temp directories writable by web server
  file: path=/var/www/roundcube/{{ item }} mode=0775 state=directory
  with_items:
    - temp
    - logs

- name: Make roundcube directory accessible to web server
  file: path=/var/www/roundcube group=www-data recurse=yes state=directory

- name: Install sieve plugin configuration
  copy: src=var_www_roundcube_plugins_managesieve_config.inc.php
    dest=/var/www/roundcube/plugins/managesieve/config.inc.php
    owner=www-data
    group=www-data
    mode=0644

- name: Install global sieve
  copy: src=var_www_roundcube_config_global.sieve
    dest=/var/www/roundcube/config/global.sieve
    owner=www-data
    group=www-data
    mode=0644

- name: Install carddav plugin configuration
  copy: src=var_www_roundcube_plugins_carddav_config.inc.php
    dest=/var/www/roundcube/plugins/carddav/config.inc.php
    owner=www-data
    group=www-data
    mode=0644

- name: Install Google 2-factor authentication plugin configuration
  copy: src=var_www_roundcube_plugins_twofactor_gauthenticator_config.inc.php
    dest=/var/www/roundcube/plugins/twofactor_gauthenticator/config.inc.php
    owner=www-data
    group=www-data
    mode=0644

- name: Configure Apache for Roundcube
  template: src=etc_apache2_sites-available_roundcube.j2
    dest=/etc/apache2/sites-available/roundcube.conf
    group=root owner=root force=yes

- name: Enable Roundcube site
  command: a2ensite roundcube.conf creates=/etc/apache2/sites-enabled/roundcube.conf
  notify: restart apache
